// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type GetUser struct {
	ID           string `json:"id"`
	ShowRoles    bool   `json:"show_roles"`
	ShowPermisos bool   `json:"show_permisos"`
}

type InputMe struct {
	ShowRoles    bool `json:"show_roles"`
	ShowPermisos bool `json:"show_permisos"`
}

type Mutation struct {
}

type NewLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewRol struct {
	Nombre      string   `json:"nombre"`
	Descripcion *string  `json:"descripcion,omitempty"`
	Jerarquia   *int     `json:"jerarquia,omitempty"`
	Permisos    []string `json:"permisos"`
}

type NewUsuario struct {
	Nombres         string   `json:"nombres"`
	Apellido1       string   `json:"apellido1"`
	Apellido2       *string  `json:"apellido2,omitempty"`
	Documento       *string  `json:"documento,omitempty"`
	Celular         *string  `json:"celular,omitempty"`
	Correo          *string  `json:"correo,omitempty"`
	Sexo            *string  `json:"sexo,omitempty"`
	Direccion       *string  `json:"direccion,omitempty"`
	Username        string   `json:"username"`
	Password        string   `json:"password"`
	Roles           []string `json:"roles"`
	PermisosSueltos []string `json:"permisos_sueltos"`
}

type Permiso struct {
	Metodo        string    `json:"metodo"`
	Nombre        string    `json:"nombre"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	FechaRegistro time.Time `json:"fecha_registro"`
}

type Query struct {
}

type QueryUsuarios struct {
	Rol *string `json:"rol,omitempty"`
}

type ResponseLogin struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type ResponseMe struct {
	Usuario         *Usuario             `json:"usuario"`
	Roles           []*ResponseRolMe     `json:"roles"`
	PermisosSueltos []*ResponsePermisoMe `json:"permisos_sueltos"`
}

type ResponsePermisoMe struct {
	Metodo        string    `json:"metodo"`
	Nombre        string    `json:"nombre"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	FechaRegistro time.Time `json:"fecha_registro"`
	FechaAsignado time.Time `json:"fecha_asignado"`
}

type ResponseRolCreate struct {
	Nombre        string               `json:"nombre"`
	Descripcion   *string              `json:"descripcion,omitempty"`
	Jerarquia     int                  `json:"jerarquia"`
	FechaRegistro time.Time            `json:"fecha_registro"`
	Permisos      []*ResponsePermisoMe `json:"permisos"`
}

type ResponseRolMe struct {
	Nombre        string               `json:"nombre"`
	Descripcion   *string              `json:"descripcion,omitempty"`
	Jerarquia     int                  `json:"jerarquia"`
	FechaRegistro time.Time            `json:"fecha_registro"`
	UsuarioID     string               `json:"usuario_id"`
	FechaAsignado time.Time            `json:"fecha_asignado"`
	Permisos      []*ResponsePermisoMe `json:"permisos"`
}

type Rol struct {
	Nombre        string    `json:"nombre"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	Jerarquia     int       `json:"jerarquia"`
	FechaRegistro time.Time `json:"fecha_registro"`
}

type UpdateUsuario struct {
	ID              string   `json:"id"`
	Nombres         string   `json:"nombres"`
	Apellido1       string   `json:"apellido1"`
	Apellido2       *string  `json:"apellido2,omitempty"`
	Documento       *string  `json:"documento,omitempty"`
	Celular         *string  `json:"celular,omitempty"`
	Correo          *string  `json:"correo,omitempty"`
	Sexo            *string  `json:"sexo,omitempty"`
	Direccion       *string  `json:"direccion,omitempty"`
	Username        string   `json:"username"`
	Password        string   `json:"password"`
	Roles           []string `json:"roles"`
	PermisosSueltos []string `json:"permisos_sueltos"`
}

type Usuario struct {
	ID            string    `json:"id"`
	Nombres       string    `json:"nombres"`
	Apellido1     string    `json:"apellido1"`
	Apellido2     *string   `json:"apellido2,omitempty"`
	Documento     *string   `json:"documento,omitempty"`
	Celular       *string   `json:"celular,omitempty"`
	Correo        *string   `json:"correo,omitempty"`
	Sexo          *string   `json:"sexo,omitempty"`
	Direccion     *string   `json:"direccion,omitempty"`
	Username      string    `json:"username"`
	FechaRegistro time.Time `json:"fecha_registro"`
	FechaUpdate   time.Time `json:"fecha_update"`
	Estado        bool      `json:"estado"`
}
